// Generated by FlutterFire CLI.
// Run: flutterfire configure --project=hamilton44-a092a
// to regenerate this file with real values.
//
// IMPORTANT: This is a PLACEHOLDER. Replace with real values from:
//   Firebase Console → Project Settings → Your Apps → SDK setup and configuration
//
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── REPLACE ALL VALUES BELOW ───────────────────────────────────────────────
  // Firebase Console → Project Settings → General → Your apps
  // ────────────────────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd8iEMpxv57Krp8WTwoVUqerhf0TL0yBM',
    appId: '1:871124539933:android:5278653686bfbb237384f4',
    messagingSenderId: '871124539933',
    projectId: 'hamilton44-a092a',
    storageBucket: 'hamilton44-a092a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIP1XkqRd7bkGEUKczGKHRui7hrbQWKg',
    appId: '1:871124539933:ios:587f518ea66751227384f4',
    messagingSenderId: '871124539933',
    projectId: 'hamilton44-a092a',
    storageBucket: 'hamilton44-a092a.firebasestorage.app',
    iosBundleId: 'com.hamilton.car.hamiltonCarService',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMCziqt09G8AJm5nmVSoMTYa4Vq-YXKk',
    appId: '1:871124539933:web:36c0ef87a759f4df7384f4',
    messagingSenderId: '871124539933',
    projectId: 'hamilton44-a092a',
    authDomain: 'hamilton44-a092a.firebaseapp.com',
    storageBucket: 'hamilton44-a092a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIIP1XkqRd7bkGEUKczGKHRui7hrbQWKg',
    appId: '1:871124539933:ios:587f518ea66751227384f4',
    messagingSenderId: '871124539933',
    projectId: 'hamilton44-a092a',
    storageBucket: 'hamilton44-a092a.firebasestorage.app',
    iosBundleId: 'com.hamilton.car.hamiltonCarService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDMCziqt09G8AJm5nmVSoMTYa4Vq-YXKk',
    appId: '1:871124539933:web:e26692712ef6c1907384f4',
    messagingSenderId: '871124539933',
    projectId: 'hamilton44-a092a',
    authDomain: 'hamilton44-a092a.firebaseapp.com',
    storageBucket: 'hamilton44-a092a.firebasestorage.app',
  );
}
